#!/bin/sh

<prof.h >README.md awk '
BEGIN                  { first_doc = 1 }
/^ \*\/$/              { def = NR + 1; in_doc = 0 }
in_doc                 { sub(" \\* ?", ""); doc=(doc == "" ? $0 : doc "\n" $0) }
/^\/\*$/               { in_doc = 1 }
NR==def                { if (first_doc) first_doc = 0; else print "" }
NR==def && /^#define/  { NF -= 1; $1 = "###"; printf "%s\n\n%s", $0, doc; doc="" }
NR==def && !/^#define/ { print doc; doc = "" }
END                    { printf "\n%s\n\n<!-- autogenerated from prof.h -->\n", doc }
'
